drop   table constellation ;
create table constellation (
    horoscope_id    INTEGER PRIMARY KEY
  , right_ascension REAL
  , declination     REAL
);

delete from constellation ;

insert into constellation (horoscope_id, right_ascension, declination) values ('1', '0h 40m', '-38Åã722''');
insert into constellation (horoscope_id, right_ascension, declination) values ('2', '10h 0m', '+35Åã239''');
insert into constellation (horoscope_id, right_ascension, declination) values ('3', '16h 0m', '+76Åã206''');
insert into constellation (horoscope_id, right_ascension, declination) values ('4', '19h 30m', '-2Åã652''');
insert into constellation (horoscope_id, right_ascension, declination) values ('5', '22h 20m', '+13Åã980''');
insert into constellation (horoscope_id, right_ascension, declination) values ('6', '17h 10m', '+55Åã237''');
insert into constellation (horoscope_id, right_ascension, declination) values ('7', '2h 30m', '-20Åã441''');
insert into constellation (horoscope_id, right_ascension, declination) values ('8', '6h 0m', '-42Åã657''');
insert into constellation (horoscope_id, right_ascension, declination) values ('9', '14h 35m', '-30Åã907''');
insert into constellation (horoscope_id, right_ascension, declination) values ('10', '4h 50m', '+38Åã125''');
insert into constellation (horoscope_id, right_ascension, declination) values ('11', '5h 40m', '-70Åã757''');
insert into constellation (horoscope_id, right_ascension, declination) values ('12', '20h 50m', '+20Åã414''');
insert into constellation (horoscope_id, right_ascension, declination) values ('13', '8h 40m', '+62Åã494''');
insert into constellation (horoscope_id, right_ascension, declination) values ('14', '1h 0m', '-60Åã598''');
insert into constellation (horoscope_id, right_ascension, declination) values ('15', '13h 20m', '+47Åã1060''');
insert into constellation (horoscope_id, right_ascension, declination) values ('16', '22h 0m', '-70Åã588''');
insert into constellation (horoscope_id, right_ascension, declination) values ('17', '1h 45m', '+12Åã1231''');
insert into constellation (horoscope_id, right_ascension, declination) values ('18', '10h 40m', '+78Åã132''');
insert into constellation (horoscope_id, right_ascension, declination) values ('19', '14h 50m', '+63Åã93''');
insert into constellation (horoscope_id, right_ascension, declination) values ('20', '6h 40m', '+24Åã380''');
insert into constellation (horoscope_id, right_ascension, declination) values ('21', '7h 30m', '-6Åã183''');
insert into constellation (horoscope_id, right_ascension, declination) values ('22', '8h 30m', '-20Åã506''');
insert into constellation (horoscope_id, right_ascension, declination) values ('23', '5h 40m', '+34Åã270''');
insert into constellation (horoscope_id, right_ascension, declination) values ('24', '12h 40m', '-23Åã386''');
insert into constellation (horoscope_id, right_ascension, declination) values ('25', '18h 30m', '+41Åã128''');
insert into constellation (horoscope_id, right_ascension, declination) values ('26', '15h 40m', '-30Åã179''');
insert into constellation (horoscope_id, right_ascension, declination) values ('27', '11h 20m', '+15Åã282''');
insert into constellation (horoscope_id, right_ascension, declination) values ('28', '12h 20m', '+60Åã68''');
insert into constellation (horoscope_id, right_ascension, declination) values ('29', '12h 20m', '+18Åã184''');
insert into constellation (horoscope_id, right_ascension, declination) values ('30', '13h 0m', '-40Åã465''');
insert into constellation (horoscope_id, right_ascension, declination) values ('31', '20h 30m', '-43Åã804''');
insert into constellation (horoscope_id, right_ascension, declination) values ('32', '20h 40m', '-12Åã189''');
insert into constellation (horoscope_id, right_ascension, declination) values ('33', '5h 0m', '+60Åã179''');
insert into constellation (horoscope_id, right_ascension, declination) values ('34', '17h 0m', '-60Åã1083''');
insert into constellation (horoscope_id, right_ascension, declination) values ('35', '21h 10m', '-6Åã72''');
insert into constellation (horoscope_id, right_ascension, declination) values ('36', '3h 50m', '+30Åã1138''');
insert into constellation (horoscope_id, right_ascension, declination) values ('37', '2h 30m', '+33Åã398''');
insert into constellation (horoscope_id, right_ascension, declination) values ('38', '7h 0m', '-22Åã514''');
insert into constellation (horoscope_id, right_ascension, declination) values ('39', '22h 20m', '+47Åã366''');
insert into constellation (horoscope_id, right_ascension, declination) values ('40', '17h 10m', '-27Åã1225''');
insert into constellation (horoscope_id, right_ascension, declination) values ('41', '3h 20m', '+52Åã249''');
insert into constellation (horoscope_id, right_ascension, declination) values ('42', '10h 30m', '+20Åã1303''');
insert into constellation (horoscope_id, right_ascension, declination) values ('43', '2h 40m', '+70Åã243''');
insert into constellation (horoscope_id, right_ascension, declination) values ('44', '21h 20m', '+58Åã294''');
insert into constellation (horoscope_id, right_ascension, declination) values ('45', '22h 25m', '-43Åã201''');
insert into constellation (horoscope_id, right_ascension, declination) values ('46', '10h 30m', '-15Åã947''');
insert into constellation (horoscope_id, right_ascension, declination) values ('47', '5h 25m', '+20Åã290''');
insert into constellation (horoscope_id, right_ascension, declination) values ('48', '15h 10m', '+14Åã538''');
insert into constellation (horoscope_id, right_ascension, declination) values ('49', '10h 20m', '-33Åã232''');
insert into constellation (horoscope_id, right_ascension, declination) values ('50', '15h 0m', '+40Åã334''');
insert into constellation (horoscope_id, right_ascension, declination) values ('51', '7h 50m', '-45Åã545''');
insert into constellation (horoscope_id, right_ascension, declination) values ('52', '18h 45m', '-36Åã286''');
insert into constellation (horoscope_id, right_ascension, declination) values ('53', '5h 40m', '+77Åã153''');
insert into constellation (horoscope_id, right_ascension, declination) values ('54', '20h 50m', '+37Åã210''');
insert into constellation (horoscope_id, right_ascension, declination) values ('55', '7h 0m', '+3Åã482''');
insert into constellation (horoscope_id, right_ascension, declination) values ('56', '12h 30m', '+70Åã138''');
insert into constellation (horoscope_id, right_ascension, declination) values ('57', '16h 0m', '+50Åã165''');
insert into constellation (horoscope_id, right_ascension, declination) values ('58', '21h 0m', '+87Åã291''');
insert into constellation (horoscope_id, right_ascension, declination) values ('59', '17h 10m', '+5Åã948''');
insert into constellation (horoscope_id, right_ascension, declination) values ('60', '5h 20m', '-3Åã594''');
insert into constellation (horoscope_id, right_ascension, declination) values ('61', '19h 10m', '+65Åã378''');
insert into constellation (horoscope_id, right_ascension, declination) values ('62', '22h 30m', '-17Åã1121''');
insert into constellation (horoscope_id, right_ascension, declination) values ('63', '3h 20m', '-42Åã615''');
insert into constellation (horoscope_id, right_ascension, declination) values ('64', '1h 0m', '+48Åã469''');
insert into constellation (horoscope_id, right_ascension, declination) values ('65', '5h 30m', '+52Åã247''');
insert into constellation (horoscope_id, right_ascension, declination) values ('66', '22h 10m', '+32Åã245''');
insert into constellation (horoscope_id, right_ascension, declination) values ('67', '0h 20m', '-10Åã889''');
insert into constellation (horoscope_id, right_ascension, declination) values ('68', '7h 40m', '+32Åã673''');
insert into constellation (horoscope_id, right_ascension, declination) values ('69', '8h 50m', '+28Åã221''');
insert into constellation (horoscope_id, right_ascension, declination) values ('70', '3h 50m', '+63Åã114''');
insert into constellation (horoscope_id, right_ascension, declination) values ('71', '0h 30m', '+35Åã475''');
insert into constellation (horoscope_id, right_ascension, declination) values ('72', '16h 30m', '+26Åã497''');
insert into constellation (horoscope_id, right_ascension, declination) values ('73', '18h 35m', '+10Åã109''');
insert into constellation (horoscope_id, right_ascension, declination) values ('74', '15h 35m', '-10Åã428''');
insert into constellation (horoscope_id, right_ascension, declination) values ('75', '18h 0m', '+5Åã208''');
insert into constellation (horoscope_id, right_ascension, declination) values ('76', '10h 10m', '+1Åã314''');
insert into constellation (horoscope_id, right_ascension, declination) values ('77', '19h 40m', '-18Åã80''');
insert into constellation (horoscope_id, right_ascension, declination) values ('78', '19h 0m', '+25Åã867''');
insert into constellation (horoscope_id, right_ascension, declination) values ('79', '4h 30m', '-18Åã797''');
insert into constellation (horoscope_id, right_ascension, declination) values ('80', '19h 0m', '+52Åã252''');
insert into constellation (horoscope_id, right_ascension, declination) values ('81', '15h 40m', '+65Åã110''');
insert into constellation (horoscope_id, right_ascension, declination) values ('82', '2h 0m', '-32Åã132''');
insert into constellation (horoscope_id, right_ascension, declination) values ('83', '23h 45m', '+68Åã295''');
insert into constellation (horoscope_id, right_ascension, declination) values ('84', '11h 0m', '-58Åã1280''');
insert into constellation (horoscope_id, right_ascension, declination) values ('85', '15h 40m', '-78Åã256''');
insert into constellation (horoscope_id, right_ascension, declination) values ('86', '9h 30m', '+45Åã500''');
insert into constellation (horoscope_id, right_ascension, declination) values ('87', '13h 20m', '+2Åã1294''');
insert into constellation (horoscope_id, right_ascension, declination) values ('88', '7h 40m', '+69Åã141''');
insert into constellation (horoscope_id, right_ascension, declination) values ('89', '20h 10m', '-25Åã268''');

select * from constellation ;
