drop   table fk_name ;
create table fk_name (
    id      
  , hip_num         INTEGER
  , horoscope_code  TEXT
  , bayer_code      TEXT
);

delete from fk_name ;

insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '122', 'Oct', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '154', 'Psc', '30');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '301', 'Cet', '2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '377', 'Tuc', '45 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '560', 'Cet', '9 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '841', 'And', '22');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '950', 'Scl', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '1007', 'Oct', 'o');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '1168', 'Peg', 'É‘');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '1473', 'And', 'É–');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '1493', 'And', 'Pi 0 h 38');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '1562', 'Cet', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '1599', 'Tuc', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '1600', 'Cet', '[-18^o 41]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '1645', 'Psc', 'd');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '1686', 'And', 'Éœ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '2006', 'Psc', '44');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '2021', 'Hyi', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '2224', 'Psc', '48');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '2381', 'Cet', '49 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '2599', 'Cas', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '2661', 'Scl', '77 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '2711', 'Phe', '58 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '2920', 'Cas', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '3031', 'And', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '3245', 'Phe', 'É ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '3344', 'Scl', 'Lac 181');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '3419', 'Cet', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '3456', 'Scl', 'É…2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '3521', 'Phe', '70 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '3781', 'Hyi', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '3786', 'Psc', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '3909', 'Cet', 'É”2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '4147', 'Cet', '20');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '4293', 'Tuc', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '4510', 'Psc', 'h');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '4577', 'Scl', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '4592', 'Cet', '98 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '4801', 'Cet', '101 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '4829', 'Phe', '80 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '4852', 'Scl', 'É–');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '4906', 'Psc', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '5170', 'Cet', '106 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '5268', 'Tuc', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '5364', 'Cet', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '5372', 'Cep', '43 H.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '5571', 'Psc', 'É‘');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '5586', 'Psc', 'É—');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '5626', 'Cep', '44 H.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '5661', 'Scl', '102 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '6061', 'Psc', 'f');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '6193', 'Psc', 'É“');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '6411', 'And', 'ÉÃ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '6502', 'Scl', '109 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '6537', 'Cet', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '6605', 'Cet', '138 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '6631', 'Hyi', '9 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '6686', 'Cas', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '6732', 'Psc', '94');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '6748', 'Cet', '47');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '7083', 'Phe', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '7513', 'And', 'É“');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '7607', 'And', '51');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '7884', 'Psc', 'ÉÀ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '7941', 'Scl', '129 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '7943', 'Tri', '[+34^o 297]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '7965', 'Cas', '43');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '7999', 'Cet', '175 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '8102', 'Cet', 'É—');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '8198', 'Psc', 'ÉÕ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '8387', 'Ari', '4');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '8837', 'Phe', 'É’');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '8886', 'Cas', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '8928', 'Hyi', 'É≈2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '9347', 'Cet', 'É“');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '9505', 'Per', 'g');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '9598', 'Cas', '50');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '9677', 'For', 'ÉÀ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '9884', 'Ari', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '10155', 'Ari', '15');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '10320', 'For', 'É ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '10328', 'Ari', '19');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '10440', 'Phe', '135 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '10602', 'Eri', 'É”');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '10623', 'Cep', 'Br 256');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '10642', 'Cet', '67');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '10670', 'Tri', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '10673', 'For', '21 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '10732', 'Ari', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '10768', 'Oct', 'Lac 1848');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '10819', 'And', 'c');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '10993', 'Oct', 'Lac 1029');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '11001', 'Hyi', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '11033', 'Cet', '239 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '11095', 'Hyi', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '11258', 'Hor', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '11345', 'Cet', 'Éœ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '11407', 'Eri', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '11486', 'Tri', '12');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '11698', 'Ari', '27');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '11783', 'Cet', 'É–');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '11784', 'Tri', '14');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '11867', 'For', 'É…1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '12107', 'Cet', '80');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '12273', 'Cas', '36 H.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '12387', 'Cet', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '12394', 'Hyi', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '12486', 'Eri', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '12768', 'Per', '14');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '12770', 'Cet', 'ÉŒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '13327', 'Ari', 'É–');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '13701', 'Eri', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '13717', 'Eri', '40 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '13834', 'Ari', '47');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '13905', 'Per', '24');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '13954', 'Cet', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '14117', 'Eri', '[-18^o 516]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '14135', 'Cet', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '14146', 'Eri', 'É—3');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '14187', 'Eri', '58 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '14240', 'Hor', 'É ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '14354', 'Per', 'Éœ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '14501', 'Eri', '63 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '14632', 'Per', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '14677', 'Ari', '55');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '14838', 'Ari', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '14930', 'Hor', '38 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '15110', 'Ari', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '15201', 'Hyi', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '15265', 'For', 'Lac 1044');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '15457', 'Cet', 'É»1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '15510', 'Eri', 'e');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '15863', 'Per', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '15890', 'Cam', 'Pi 3 h 27');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '16335', 'Per', 'É–');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '16341', 'Eri', 'v');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '16509', 'Hor', '45 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '16518', 'Per', '[+34^o 674]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '16852', 'Tau', '10');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '17007', 'For', 'É—');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '17304', 'For', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '17378', 'Eri', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '17457', 'Eri', '24');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '17651', 'Eri', 'É—6');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '17678', 'Hyi', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '17874', 'Eri', 'g');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '18169', 'Eri', '145 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '18170', 'Tau', 'Pi 3 h 187');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '18217', 'Cam', '[+57^o 752]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '18592', 'Ret', '17 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '18597', 'Ret', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '18614', 'Per', 'ÉÃ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '18729', 'Hyi', '63 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '18788', 'Eri', '35');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '18907', 'Tau', 'ÉÀ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '19038', 'Tau', '37');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '19095', 'Eri', '174 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '19167', 'Per', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '19388', 'Tau', 'É÷1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '19513', 'Tau', 'p');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '19587', 'Eri', 'ÉÕ1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '19747', 'Hor', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '19860', 'Tau', 'É ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '19893', 'Dor', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '20049', 'Men', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '20252', 'Per', '54');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '20264', 'Eri', '212 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '20384', 'Ret', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '20507', 'Eri', 'ÉÃ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '20535', 'Eri', 'É“3');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '20884', 'Tau', 'Br 615');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '20889', 'Tau', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '20974', 'Cam', '[+69^o 258]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '21060', 'Cae', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '21242', 'Per', 'm');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '21393', 'Eri', 'É“2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '21743', 'Eri', '258 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '21861', 'Cae', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '21949', 'Men', 'É ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '22024', 'Eri', '56');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '22192', 'Eri', '268 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '22361', 'Cam', 'Grb 848');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '22449', 'Ori', 'ÉŒ3');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '22453', 'Aur', '1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '22565', 'Tau', 'i');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '22871', 'Men', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '23015', 'Aur', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '23148', 'Men', 'ÉÃ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '23446', 'Cae', '26 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '23497', 'Tau', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '23522', 'Cam', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '23607', 'Ori', '11');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '23649', 'Pic', 'É≈2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '23685', 'Lep', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '23693', 'Dor', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '23767', 'Aur', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '23833', 'Pic', '13 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '23875', 'Eri', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '23972', 'Eri', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '24305', 'Lep', 'É ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '24372', 'Dor', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '24659', 'Col', 'ÉÕ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '24813', 'Aur', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '24829', 'Pic', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '24831', 'Col', '12 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '24845', 'Lep', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '25336', 'Ori', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '25769', 'Cam', '17');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '25911', 'Cep', '1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '25973', 'Cam', '[+85^o 74]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '26311', 'Ori', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '26495', 'Col', '35 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '26638', 'Cam', 'Grb 966');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '26661', 'Oct', '6 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '27100', 'Dor', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '27288', 'Lep', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '27338', 'Tau', '130');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '27366', 'Ori', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '27435', 'Ori', '142 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '27530', 'Pic', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '27621', 'Pic', '37 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '27628', 'Col', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '27654', 'Lep', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '27949', 'Aur', 'ÉÃ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '28103', 'Lep', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '28328', 'Col', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '28429', 'Aur', '[+33^o 1209]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '28532', 'Cep', 'Grb 944');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '28814', 'Ori', '66');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '28899', 'Col', '74 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '29134', 'Dor', 'ÉÀ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '29271', 'Men', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '29490', 'Cam', '36');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '29696', 'Aur', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '29807', 'Col', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '29997', 'Cam', '22 H.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '30324', 'CMa', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '30343', 'Gem', 'É ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '30438', 'Car', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '30457', 'CMa', '23 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '30520', 'Aur', 'É’1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '30640', 'Aur', 'Grb 1156');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '30678', 'Oct', 'A');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '30772', 'Mon', '10');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '31216', 'Mon', '13');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '31278', 'Mon', '56 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '31676', 'Lyn', '8');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '31685', 'Pup', 'ÉÀ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '31771', 'Aur', '51');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '31897', 'Men', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '32246', 'Gem', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '32362', 'Gem', 'ÉÃ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '32500', 'Oct', '7 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '32537', 'Pup', 'x');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '32562', 'Aur', 'É’6');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '32759', 'CMa', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '32912', 'Vol', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '33018', 'Gem', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '33104', 'Cam', '43');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '33160', 'CMa', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '33694', 'Cam', '24 H.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '33927', 'Gem', 'É÷');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '33977', 'CMa', 'ÉÕ2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '34045', 'CMa', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '34088', 'Gem', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '34387', 'CMi', '2 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '34444', 'CMa', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '34752', 'Aur', '63');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '34834', 'Pup', 'I');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '35136', 'Lyn', 'Grb 1281');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '35228', 'Vol', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '35341', 'Aur', '64');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '35904', 'CMa', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '35907', 'Aur', '66');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '36046', 'Gem', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '36425', 'CMi', '6');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '36795', 'Pup', '108 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '36942', 'Car', 'Q');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '37023', 'Lyn', '[+46^o 1286]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '37036', 'Pup', '125 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '37391', 'Cep', '51 H.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '37447', 'Mon', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '37891', 'Pup', '4');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '37921', 'CMi', '11');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '37946', 'Lyn', '[+37^o 1769]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '38373', 'CMi', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '38639', 'Lyn', '26');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '38848', 'Cnc', '1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '38901', 'Pup', '225 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '38959', 'Lyn', 'Grb 1384');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '39079', 'Mon', '27');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '39095', 'Pup', '232 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '39117', 'Cam', 'Grb 1374');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '39191', 'Cnc', 'É÷1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '39326', 'Mon', '161 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '39429', 'Pup', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '40215', 'UMa', '3 H.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '40259', 'Pup', '20');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '40559', 'Cam', '[Grb 1359]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '40706', 'Pup', 'q');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '40766', 'Hya', '7 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '40793', 'Cam', 'Br 1147');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '40843', 'Cnc', 'É‘');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '40945', 'Pup', 'w');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '41075', 'Lyn', '31');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '41307', 'Hya', 'C');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '41312', 'Vol', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '41578', 'Cnc', '29');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '41909', 'Cnc', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '41935', 'Lyn', '[Grb 1450]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '42312', 'Vel', 'e');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '42313', 'Hya', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '42402', 'Hya', 'É–');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '42452', 'UMa', 'Grb 1460');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '42484', 'Cam', 'Grb 1446');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '42509', 'Hya', 'a');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '42604', 'Lyn', '34');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '42637', 'Cha', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '42806', 'Cnc', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '42828', 'Pyx', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '42928', 'Pyx', '25 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '43305', 'Hya', '14');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '43409', 'Pyx', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '43798', 'Hya', '80 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '43813', 'Hya', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '43908', 'Oct', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '44356', 'Hya', '92 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '44382', 'Vol', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '44390', 'UMa', 'Éœ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '44476', 'Hya', '93 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '44504', 'UMa', 'Grb 1501');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '44511', 'Vel', 'c');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '44700', 'Lyn', 'Pi 8 h 245');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '44936', 'Hya', '101 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '45158', 'Hya', '107 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '45238', 'Car', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '45290', 'Lyn', '36');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '45421', 'Cam', '[+84^o 196]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '45556', 'Car', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '45699', 'Cnc', '83');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '45860', 'Lyn', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '45902', 'Pyx', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '46221', 'Hya', '28');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '46390', 'Hya', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '46515', 'Ant', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '46701', 'Vel', 'N');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '46741', 'Car', 'H');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '46880', 'Hya', '160 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '46952', 'LMi', '10');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '46977', 'UMa', 'd');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '47193', 'Dra', '1 H.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '47199', 'Ant', '17 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '47310', 'Sex', '2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '47431', 'Hya', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '47452', 'Hya', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '47594', 'UMa', 'Grb 1564');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '47701', 'Leo', 'f');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '47723', 'Leo', 'É’');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '47854', 'Car', 'l');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '47908', 'Leo', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '47909', 'Leo', '[+19^o 2254]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '48113', 'UMa', 'Br 1369');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '48341', 'Sex', '6');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '48455', 'Leo', 'É ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '48615', 'Hya', '183 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '48712', 'Sex', '18 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '49029', 'Leo', 'ÉŒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '49339', 'Hya', '193 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '49363', 'UMa', 'Pi 9 h 229');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '49402', 'Hya', 'É“2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '50099', 'Car', 'É÷');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '50191', 'Vel', 'q');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '50335', 'Leo', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '50414', 'Sex', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '50448', 'UMa', '32');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '50684', 'Sex', '23');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '50799', 'Vel', 'r');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '50860', 'LMi', '27');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '50885', 'Sex', '25');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '50888', 'Ant', '64 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '50954', 'Car', 'I');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '51069', 'Hya', 'É ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '51172', 'Ant', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '51232', 'Car', 's');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '51362', 'Sex', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '51399', 'LMi', '[+29^o 2057]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '51472', 'Oct', '10 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '51576', 'Car', 'p');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '51585', 'Leo', '46');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '51808', 'Dra', '9 H.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '51814', 'UMa', '37');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '51839', 'Cha', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '52098', 'LMi', '37');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '52316', 'Sex', '33');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '52425', 'UMa', '35 H.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '52457', 'LMi', '41');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '52633', 'Cha', 'É¬2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '52638', 'LMi', '42');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '52660', 'Leo', 'Br 1493');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '52686', 'Leo', 'm');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '52721', 'Hya', '250 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '52911', 'Leo', 'l');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '52943', 'Hya', 'ÉÀ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '53229', 'LMi', '46');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '53502', 'Ant', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '53702', 'Oct', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '53721', 'UMa', '47');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '53740', 'Crt', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '53761', 'Dra', 'Br 1508');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '53773', 'Vel', 'i');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '53910', 'UMa', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '54214', 'Crt', '11 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '54463', 'Car', 'x');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '54539', 'UMa', 'É’');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '54725', 'Hya', '275 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '54872', 'Leo', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '54879', 'Leo', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '54901', 'Cam', '[+86^o 161]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '55084', 'Leo', 'É”');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '55086', 'UMa', 'Grb 1757');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '55282', 'Crt', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '55434', 'Leo', 'É–');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '55564', 'UMa', 'Grb 1771');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '55667', 'Cen', '28 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '55781', 'Leo', 'Pi 11 h 63');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '55945', 'Leo', 'É—');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '56076', 'Hya', '282 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '56148', 'UMa', '58');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '56211', 'Dra', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '56343', 'Hya', 'ÉÃ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '56573', 'Cen', 'C2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '56633', 'Crt', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '56647', 'Leo', 'É“');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '56922', 'Hya', 'ÉÕ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '56997', 'UMa', '61');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '57111', 'Dra', '3');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '57380', 'Vir', 'ÉÀ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '57399', 'UMa', 'É‘');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '57498', 'UMa', 'Grb 1826');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '57613', 'Hya', '298 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '57757', 'Vir', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '57803', 'Cen', 'B');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '57939', 'UMa', 'Grb 1830');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '58001', 'UMa', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '58188', 'Crt', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '58803', 'Cen', '88 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '58874', 'Cam', 'Grb 1850');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '58948', 'Vir', 'ÉÕ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '58952', 'Cam', 'Grb 1852');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '59316', 'Crv', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '59708', 'UMa', 'Br 1636');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '59747', 'Cru', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '59774', 'UMa', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '59803', 'Crv', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '60000', 'Cha', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '60122', 'CVn', '3');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '60172', 'Vir', 'c');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '60603', 'Hya', '322 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '60646', 'CVn', '6');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '60735', 'Hya', '323 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '60823', 'Cen', 'É–');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '60855', 'Cen', 'u');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '60957', 'Com', '20');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '61084', 'Cru', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '61199', 'Mus', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '61296', 'Crv', '35 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '61309', 'CVn', 'Pi 12 h 122');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '61359', 'Crv', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '61558', 'Vir', 'f');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '61740', 'Vir', 'É‘');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '61916', 'Cen', '133 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '61936', 'UMa', '76');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '61960', 'Vir', 'Éœ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '62131', 'Hya', '330 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '62223', 'CVn', 'Y');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '62443', 'Vir', '35');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '62448', 'Hya', '332 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '62763', 'Com', '31');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '62807', 'Com', '32');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '62896', 'Cen', 'n');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '62985', 'Vir', 'É’');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '63076', 'Dra', '8');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '63090', 'Vir', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '63608', 'Vir', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '63901', 'CVn', '14');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '64053', 'Cen', '177 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '64246', 'CVn', '17');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '64394', 'Com', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '64803', 'Cen', 'r');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '64844', 'CVn', '20');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '64852', 'Vir', 'É–');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '64924', 'Vir', '61');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '64962', 'Hya', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '65072', 'CVn', '23');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '65109', 'Cen', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '65581', 'Vir', 'i');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '65709', 'CVn', '[+31^o 2493]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '65721', 'Vir', '70');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '66200', 'Vir', 'o');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '66249', 'Vir', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '66294', 'CVn', 'Grb 2017');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '66320', 'Vir', '80');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '66435', 'UMi', 'Grb 2029');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '66607', 'Cha', '49 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '66753', 'Oct', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '66803', 'Vir', 'm');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '66878', 'Cam', 'Grb 2063');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '66925', 'Cen', '253 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '67057', 'Vir', '83');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '67301', 'UMa', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '67481', 'Boo', '[+9^o 2814]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '67494', 'Vir', '89');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '68065', 'CVn', '[+32^o 2411]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '68191', 'Cen', '294 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '68269', 'Hya', '47');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '68390', 'Hya', '48');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '68478', 'Boo', '11');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '68520', 'Vir', 'É—');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '68673', 'Cen', '307 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '68763', 'Vir', '210 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '68888', 'Vir', '94');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '68895', 'Hya', 'ÉŒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '68933', 'Cen', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '69038', 'Boo', '9 H.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '69427', 'Vir', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '69701', 'Vir', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '69732', 'Boo', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '69989', 'Boo', '18');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '70069', 'Cen', 'v');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '70336', 'Lib', '2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '70400', 'Vir', '244 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '70469', 'Lib', '3 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '70492', 'Cir', '10 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '70574', 'Lup', 'É—1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '70602', 'Boo', 'f');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '71040', 'Dra', 'Grb 2125');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '71284', 'Boo', 'É–');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '71352', 'Cen', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '71618', 'Boo', '33');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '71837', 'Boo', '32');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '71957', 'Vir', 'É ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '71995', 'Boo', '34');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '72010', 'Cen', 'c1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '72124', 'Boo', '[+33^o 2489]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '72220', 'Vir', '19');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '72357', 'Hya', '56');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '72370', 'Aps', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '72469', 'Boo', 'Grb 2152');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '72573', 'UMi', 'Grb 2196');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '72607', 'UMi', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '72664', 'Dra', 'Grb 2164');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '72869', 'Vir', '[+6^o 2957]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '73087', 'Boo', '[Pi 14 h 221]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '73133', 'Lib', 'ÉÃ2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '73156', 'Boo', '[Pi 14 h 227]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '73273', 'Lup', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '73555', 'Boo', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '73714', 'Lib', 'É–');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '73745', 'Boo', 'É’');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '73909', 'Boo', '[+55^o 1730]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '73996', 'Boo', 'c');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '74604', 'Lup', 'i');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '74605', 'UMi', '1 H.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '74785', 'Lib', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '74824', 'Cir', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '74946', 'TrA', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '75097', 'UMi', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '75288', 'Lib', '73 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '75294', 'Lib', '30');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '75304', 'Lup', 'É”2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '75342', 'Ser', '8');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '75458', 'Dra', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '75530', 'Ser', 'É—1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '75730', 'Lib', 'Éƒ1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '75971', 'Ser', '[+9^o 3055]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '75973', 'Boo', 'ÉÀ1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '76219', 'Lib', '37');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '76397', 'Lup', '115 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '76440', 'TrA', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '76534', 'Boo', 'É”');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '76996', 'Oct', 'Éœ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '77013', 'UMi', 'Grb 2315');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '77055', 'UMi', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '77277', 'Dra', '12 H.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '77450', 'Ser', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '77622', 'Ser', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '77655', 'CrB', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '78072', 'Ser', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '78180', 'Dra', 'Grb 2296');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '78207', 'Lib', '48');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '78323', 'Lup', '144 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '78436', 'Lib', '50');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '79137', 'Ser', '[+6^o 3169]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '79280', 'UMi', '19');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '79593', 'Oph', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '79724', 'Her', '17');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '80047', 'Aps', 'É¬1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '80179', 'Ser', 'É–');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '80375', 'Dra', 'Grb 2343');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '80650', 'Dra', '15');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '80850', 'UMi', 'Grb 2373');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '80911', 'Sco', 'N');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '80991', 'Dra', 'Pi 16 h 140');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '81065', 'Aps', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '81266', 'Sco', 'É—');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '81300', 'Oph', '12');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '81377', 'Oph', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '81724', 'Oph', 'Br 2114');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '81833', 'Her', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '82273', 'TrA', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '82351', 'Oph', '[-21^o 4422]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '82396', 'Sco', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '82504', 'Her', '51');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '82526', 'Her', '49');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '82587', 'Her', '53');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '82673', 'Oph', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '83000', 'Oph', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '83057', 'Ara', '24 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '83081', 'Ara', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '83153', 'Ara', 'É√1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '83255', 'Oct', '26 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '83262', 'Oph', '30');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '83313', 'Her', 'd');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '83593', 'Her', 'Pi 16 h 307');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '83613', 'Her', '60');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '83740', 'Oph', '80 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '83854', 'Oph', '85 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '83962', 'Oph', '88 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '84113', 'Oph', '97 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '84143', 'Sco', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '84380', 'Her', 'ÉŒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '84551', 'Sco', '139 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '84862', 'Her', 'w');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '85258', 'Ara', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '85307', 'Oph', '138 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '85340', 'Oph', 'b');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '85355', 'Oph', 'É–');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '85379', 'Her', 'x');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '85423', 'Oph', 'd');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '85693', 'Her', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '85696', 'Sco', 'É“');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '85760', 'Aps', '59 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '85805', 'Dra', 'f');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '85822', 'UMi', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '85888', 'Her', 'Grb 2444');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '86670', 'Sco', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '86736', 'Oph', '58');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '86742', 'Oph', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '86796', 'Ara', 'É ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '86929', 'Pav', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '87072', 'Sgr', '3');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '87108', 'Oph', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '87158', 'Her', '[+20^o 3570]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '87234', 'Dra', '35');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '87289', 'Oph', '[+9^o 3485]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '87585', 'Dra', 'ÉÃ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '87710', 'Oph', '[-7^o 4523]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '87808', 'Her', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '87933', 'Her', 'ÉÃ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '88048', 'Oph', 'ÉÀ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '88128', 'Her', '93');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '88258', 'Sgr', '6');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '88635', 'Sgr', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '88714', 'Ara', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '88981', 'Ser', '[-13^o 4863]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '89348', 'Dra', '36');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '89482', 'Lyr', 'Grb 2533');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '89605', 'Tel', '6 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '89826', 'Lyr', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '89962', 'Ser', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '90139', 'Her', '109');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '90422', 'Tel', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '90496', 'Sgr', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '90595', 'Sct', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '90642', 'Ser', 'c');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '90647', 'Dra', 'Grb 2655');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '90762', 'Her', '[+16^o 3529]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '90982', 'CrA', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '90999', 'Lyr', 'Grb 2603');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '91117', 'Sct', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '91262', 'Lyr', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '92041', 'Sgr', 'É”');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '92088', 'Lyr', '[+26^o 3349]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '92609', 'Pav', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '92824', 'Oct', 'É‘');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '92855', 'Sgr', 'É–');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '92862', 'Lyr', '13');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '92882', 'Sgr', '114 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '93148', 'Tel', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '93805', 'Aql', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '93843', 'Lyr', 'Pi 18 h 318');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '94114', 'CrA', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '94376', 'Dra', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '94385', 'Aql', '20');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '94713', 'Lyr', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '94714', 'Oct', '42 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '94779', 'Cyg', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '94834', 'Aql', 'É÷1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '94986', 'Sgr', '162 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '95167', 'Dra', 'Grb 2900');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '95347', 'Sgr', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '95447', 'Aql', 'b');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '95520', 'Dra', 'Pi 19 h 156');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '95534', 'Cyg', 'Grb 2844');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '95619', 'Sgr', '186 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '95690', 'Tel', '59 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '95771', 'Vul', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '95853', 'Cyg', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '95937', 'Aql', 'e');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '96052', 'Cyg', '8');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '96341', 'Tel', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '96483', 'Aql', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '96837', 'Sge', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '97118', 'Cyg', '15');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '97260', 'Sgr', '228 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '97278', 'Aql', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '97290', 'Sgr', 'f');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '97421', 'Tel', 'ÉÀ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '97804', 'Aql', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '97871', 'Aql', '90 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '97971', 'Pav', '75 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '98032', 'Sgr', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '98086', 'Oct', '44 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '98337', 'Sge', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '98382', 'Dra', 'Grb 3212');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '98495', 'Pav', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '98688', 'Sgr', 'c');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '98823', 'Aql', 'É—');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '99120', 'Tel', 'ÉÃ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '99240', 'Pav', 'É¬');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '99303', 'Cyg', 'b2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '99655', 'Cyg', '33');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '99742', 'Aql', 'Éœ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '99951', 'Vul', '24');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '100062', 'Cap', '4');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '100151', 'Tel', '83 G. ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '100332', 'Sgr', '290 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '100541', 'Aql', '132 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '101067', 'Cyg', '42');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '101076', 'Cyg', '41');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '101101', 'Aql', '69');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '101134', 'Dra', 'Grb 3241');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '101421', 'Del', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '101489', 'Del', '9 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '101984', 'Cap', 'É“');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '102014', 'Mic', '13 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '102098', 'Cyg', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '102205', 'Oct', '48 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '102208', 'Dra', '76');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '102333', 'Ind', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '102395', 'Pav', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '102485', 'Cap', 'É’');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '102499', 'Cyg', 'Grb 3285');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '102618', 'Aqr', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '102624', 'Aqr', 'k');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '102770', 'Aqr', '[-1^o 4057]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '102978', 'Cap', 'É÷');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '103200', 'Vul', '32');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '103460', 'Cap', '64 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '103511', 'Vul', '33');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '103682', 'Aqr', '11');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '103882', 'Mic', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '104105', 'Cep', 'Br 2777');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '104139', 'Cap', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '104189', 'Aqr', '[-0^o 4161]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '104382', 'Oct', 'É–');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '104459', 'Aqr', 'ÉÀ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '104755', 'Pav', 'ÉÕ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '105133', 'Ind', '24 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '105140', 'Mic', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '105199', 'Cep', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '105515', 'Cap', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '105841', 'Ind', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '105858', 'Pav', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '106021', 'Peg', '2 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '106093', 'Cyg', 'g');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '106429', 'Gru', '3 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '106481', 'Cyg', 'Éœ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '106787', 'Peg', '5');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '107119', 'Cep', '11');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '107315', 'Peg', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '107418', 'Cep', 'ÉÀ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '107445', 'Cyg', '[+35^o 4626]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '107517', 'Cap', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '107575', 'Peg', '11');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '107649', 'Gru', '13 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '107877', 'Cap', '127 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '108022', 'Peg', '16');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '108036', 'Cap', 'É ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '108296', 'Peg', 'Pi 21 h 339');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '108506', 'Aqr', '98 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '108870', 'Ind', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '109005', 'Cep', '20');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '109074', 'Aqr', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '109111', 'Gru', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '109139', 'Aqr', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '109400', 'Cep', '24');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '109410', 'Peg', 'ÉŒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '109492', 'Cep', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '109789', 'PsA', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '109822', 'Aqr', '125 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '110003', 'Aqr', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '110256', 'Oct', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '110386', 'Peg', '31');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '110391', 'Aqr', '47');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '110672', 'Aqr', 'ÉŒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '110696', 'Peg', 'Pi 22 h 97');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '110935', 'Ind', '72 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '110986', 'Peg', '36');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '110992', 'Peg', 'Pi 22 h 120');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '111056', 'Cep', 'Éœ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '111196', 'Oct', 'É“');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '111242', 'Cep', 'Grb 3834');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '111449', 'Aqr', 'É“');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '111497', 'Aqr', 'É≈');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '111532', 'Cep', '31');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '111710', 'Aqr', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '111797', 'Cep', '30');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '111841', 'Lac', '10');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '112029', 'Peg', 'Éƒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '112122', 'Gru', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '112355', 'Oct', 'B');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '112358', 'Peg', '45');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '112440', 'Peg', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '112520', 'Aqr', '[-2^o 5826]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '112529', 'Aqr', '68');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '112623', 'Gru', 'É√');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '112716', 'Aqr', 'É—');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '112724', 'Cep', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '112748', 'Peg', 'É ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '112832', 'Gru', '69 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '113116', 'Cep', '36 H.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '113137', 'Ind', 'Éœ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '113174', 'Lac', '[+36^o 4956]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '113881', 'Peg', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '113889', 'Psc', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '113963', 'Peg', 'Éø');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '114144', 'Peg', '55');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '114210', 'And', '5');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '114341', 'Aqr', 'c2');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '114520', 'Peg', '59');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '114622', 'Cas', 'Br 3077');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '114948', 'Tuc', '25 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '114971', 'Psc', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '115102', 'Scl', 'É¡');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '115250', 'Peg', 'É—');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '115280', 'And', '12');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '115312', 'Scl', '11 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '115438', 'Aqr', 'b1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '115590', 'Cas', '4');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '115591', 'Peg', '67');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '115623', 'Peg', 'É“');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '115713', 'Gru', 'ÉÕ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '115738', 'Psc', 'É»');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '115830', 'Psc', 'É∆');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '115836', 'Oct', 'É—');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '115910', 'Peg', '[+15^o 4830]');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '116231', 'Scl', 'É¿');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '116354', 'And', '15');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '116428', 'Aqr', '248 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '116602', 'Phe', '11 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '116631', 'And', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '116771', 'Psc', 'É«');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '116820', 'Scl', 'É ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '116928', 'Psc', 'É…');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '117089', 'Aqr', 'i1');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '117371', 'Cep', '41 H.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '117375', 'Psc', '20');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '117488', 'Aqr', 'Pi 23 h 194');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '117541', 'Aqr', '268 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '117718', 'Peg', 'É”');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '117863', 'Cas', 'Éœ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '117880', 'Phe', '27 G.');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '118027', 'Cep', 'V');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '118048', 'Peg', 'Pi 23 h 235');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '118234', 'Phe', 'ÉŒ');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '118268', 'Psc', 'É÷');
insert into fk_name (hip_num, horoscope_code, bayer_code) values ( '118322', 'Tuc', 'É√');

select * from fk_name ;
